### PR TITLE
Version 2 0 onigotez

### PR DESCRIPTION
**Pull request by garris**
@onigoetz:   I fixed some remaining issues with the travis test and browser reports in legacy mode (when referencing browser images).    I realized I unnecessarily changed `.travis.yml` -- if you want to revert that one it's ok with me.  The other stuff is solid though.

Thank you so much for your help -- these are amazing improvements!

Except for the readme (which I can update) I think it's pretty good to go.  Are there any other things you wanted to get in?

Best,
Garris

### CODE REVIEW

**Comment by onigoetz** [comment]
Thanks this is great. I will merge this tonight

My team and I wanted to do a bit of polishing today and tomorrow, so I think it can be merged on monday

**Comment by garris** [comment]
Super exciting!   I will try to look at the documentation and make sure it's in order.  

If possible -- could you post an example of a config which uses `variants`?

I usually do a small blog post for new releases -- how would you like me to credit the awesome contribution of your team?

**Comment by garris** [comment]
I found a few more issues.  

- I added a default misMatchThreshold value so that configs without that parameter don't generate false positives. 

- also added back the bower dependencies.  I didn't see these getting installed anywhere -- and I don't mind keeping these with the repo.   Ultimately that report could be much nicer -- for now it's fine that it just works.

I am presenting to the engineering group at linkedin on Tuesday next week so I wanted to try to get this ready for that.

**Comment by onigoetz** [comment]
Hello,
I'm sorry I was exhausted last night and didn't merge your changes. I will make a last round of polish this weekend
That way we're sure that everything's perfectly smooth for tuesday

Get Outlook for iOS




On Fri, Aug 26, 2016 at 2:16 AM +0200, "Garris" <notifications@github.com> wrote:












I found a few more issues.  




I added a default misMatchThreshold value so that configs without that parameter don't generate false positives. 


also added back the bower dependencies.  I didn't see these getting installed anywhere -- and I don't mind keeping these with the repo.   Ultimately that report could be much nicer -- for now it's fine that it just works.




I am presenting to the engineering group at linkedin on Tuesday next week so I wanted to try to get this ready for that.

**Comment by garris** [comment]
No worries  -- Thank you.

**Comment by onigoetz** [comment]
Awesome, thanks for all your changes

**Pull request merged**
